### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by psikoz** [romzes13/WorkOrderCMS#24]
hey @romzes13  

i deisgned a logo for you.  WDYT? If there is anything you want, please tell me. Color , font etc...

LOGO IDEA;

Gear : manage 

 Arrow: ''dispatch'' work orders.

![workorder](https://user-images.githubusercontent.com/40601249/43680091-624851a0-983b-11e8-968c-afb2db399750.jpg)

**Comment by romzes13** [comment]
Hi @psikoz,
That looks awesome!I like it! I think the color combination will blend in pretty well in the new design.

**Comment by romzes13** [comment]
@psikoz would you be able to crop it please into two different images so I can update the readme file?

**Comment by psikoz** [comment]
Ofcourse, at the end of the work I will send you all the files you need. I actually found a more compatible 
font. WDYT?

if you like it , i will send a pr.

![1](https://user-images.githubusercontent.com/40601249/43685319-6ea0ea2e-98b9-11e8-8230-e0958f5608de.jpg)

**Comment by romzes13** [comment]
I like this one as well. Can you please make the gear, which is above "WorkOrderCMS", a little smaller?

**Comment by romzes13** [comment]
I like it. Would you be able to do the same thing with the first version, make the gear smaller? I like the first version font little better. 

- Also, can you make the font in the first version little bolder? I wonder if it will help stand out a little bit more.
- Can you make the background clear please?

Thank you for your help and send the pull request please.

**Comment by psikoz** [comment]
I made changes. background? Sorry, I do not fully understand. I've no hurry. I am here to do my best. At the end of the job, I will send you a pr if you like it. How is these?

![1](https://user-images.githubusercontent.com/40601249/43780860-41214466-9a64-11e8-8fd2-353c93f3e74c.jpg)

**Comment by romzes13** [comment]
I like the version on the left. I meant, if you can make the background transparent. 
Thanks again!

**Comment by psikoz** [comment]
yeah, You mean the png version. I added the all files version and i sent a pull-request. If you need something else, feel free to say me.

**Comment by romzes13** [comment]
Awesome job! Thank you!
